### ISSUE TITLE
Cannot Install on latest Modapi; Says it requires newer version

### ISSUE THREAD

**Issue by MewtwoFanz** [Liskomato/Spore-AnimationOverrider#1]
Basically, when I try to install this mod, It says this:

![animation overide message](https://github.com/Liskomato/Spore-AnimationOverrider/assets/68346992/bdc16853-bc7c-414a-8842-cb2da9c2633a)

Can somebody figure this out?

**Comment by Tenderi4** [comment]
This issue should now be fixed with this release: https://github.com/Liskomato/Spore-AnimationOverrider/releases/tag/v1.0.1

Thank you for reporting the bug!
